[
  {
    "enable": true,
    "alias": "来荣政",
    "phone": "13303920542",
    "password": "Lairongzheng888",
    "deviceType": "HONOR|Magic4 Pro|12",
    "deviceId": "864015048850120",
    "randomLocation": true,
    "address": "中国河南省安阳市比亚迪实业有限公司",
    "longitude": "114.5174633984721",
    "latitude": "36.05933239267502",
    "pushKey": "e91a2b5c3444461a8ae3b6d205bfbeb8"
  }
]
